/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.exchange;
 
import java.awt.Dimension;
import java.io.InputStream;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.BorderPane;
import javafx.scene.web.WebEngine;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mahe
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
  int s_id;
   public int uid=0;
   String price;
   float p;
   float bal;
    public MainScreen(int myid) {
        uid = myid;
        initComponents();
        
        try{
     Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql="select balance from userDetail where id='"+uid+"'";
    ResultSet rs=stmt.executeQuery(sql);
    
    
    while(rs.next())
            {
                String b=rs.getString("balance");
                bal= Float.parseFloat(b);
                System.out.println("stock ball :"+ b);
            }
         }
         catch(Exception e)
         {
             System.out.println(e.getMessage());
         }
             
    }
   
    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        res = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Portfolio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 11, -1, -1));

        jButton1.setText("To Market");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jButton2.setText("News");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 76, -1, -1));

        jButton3.setText("Graph");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 76, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stock Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 77, 160, -1));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Buy");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 158, -1, -1));

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Sell");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 158, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 117, 46, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 120, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 120, 141, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Present Price (in $):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        res.setText("OK");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 158, 72, 26));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 202, 80, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wallet :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 205, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Name", "Quantity", "Current Price (in $)"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 409, 92));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Select a choice");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 162, 95, -1));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/exchange/img2-01.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TradeScreen trs1 = new TradeScreen(uid);
        this.dispose();
        trs1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    JEditorPane website = new JEditorPane();
        WebView wv;
    JFXPanel fxPanel;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String stock_name = (String) jComboBox2.getSelectedItem();
        try{
            String URL ="https://www.google.com/finance/company_news?q="+stock_name+"&ei=9f3nWPDLINK8uASl9Jr4Dw";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }catch(Exception e){
            System.out.println("e.getMessage()");
        }
        
        
        
        /*JEditorPane jep = new JEditorPane();
     jep.setEditable(false);   
     try {
       jep.setPage("https://www.google.com/finance/company_news?q=IBN&ei=9f3nWPDLINK8uASl9Jr4Dw");
     }
     catch (IOException e) {
       jep.setContentType("text/html");
       jep.setText("<html>Could not load http://www.oreilly.com </html>");
     } 
      JFXPanel pan = new JFXPanel();
      //WebView wv = new WebView();
      //wv.getEngine().load("http://www.google.com/");
      //pan.setScene(new Scene(wv, 1000, 500));
     JScrollPane scrollPane = new JScrollPane(jep);     
     JFrame f = new JFrame("O'Reilly & Associates");
     // Next line requires Java 1.3
     f.add(pan);
     f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     f.getContentPane().add(scrollPane);
     f.setVisible(true);
     f.setSize(512, 342);
     
     f.show(); 
     */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try{
    String stock_name = (String) jComboBox2.getSelectedItem();
    String path = "http://chart.finance.yahoo.com/z?s="+stock_name+"&t=6m&q=l";
    URL url = null;
    url = new URL(path);
    BufferedImage image = ImageIO.read(url);
    JLabel label = new JLabel(new ImageIcon(image));
    JFrame f = new JFrame();
    //f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.getContentPane().add(label);
    f.pack();
    f.setLocation(200,200);
    f.setVisible(true);
    }
    catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ButtonGroup grp = new ButtonGroup();
        grp.add(jRadioButton1);
        grp.add(jRadioButton2);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel5.setVisible(false);
         try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql="select name from stockT";
    ResultSet rs=stmt.executeQuery(sql);
    while(rs.next())
    {
        
       jComboBox2.addItem(rs.getString("name"));
       
    }
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
try{
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql="select name,sum(qty) as sm from portfolio,stockT where portfolio.sID=stockT.sID and ID='"+uid+"' group by(name);";
    ResultSet rs2 = stmt.executeQuery(sql);
    
    while (rs2.next())
    {
        
        int uni=rs2.getInt("sm");
        String st=rs2.getString("name");
        
         String po=jTextField3.getText();
         Float pp=Float.parseFloat(po);
        Float x=pp*uni;
     Object[] row = { st, uni,x };
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    jTable2.setModel(model);
        
        
        model.addRow(row);
    }// TODO add your handling code here:
    }                                 
catch(Exception e)
{
    System.out.println(e.getMessage());
}
    
    }//GEN-LAST:event_formWindowOpened

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
      try{
       String st=(String)jComboBox2.getSelectedItem();
       webscraper w=new webscraper(st);
    price=w.pr;
    jTextField3.setText(""+price);
     System.out.println("stock selected"+ st);
    jTextField4.setText(""+bal);
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql2="select sID from stockT where name = '"+st+"'";
    System.out.println("connecting");
    ResultSet rs2=stmt.executeQuery(sql2);
    while (rs2.next())
    s_id=rs2.getInt("sID");
            System.out.println("stock code   :"+s_id);
        }
        catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
       
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        if(jTextField1.equals(null) ){
            System.out.println("qty field empty");
        }else{
   
            int qty=0;
            try{
    qty=Integer.parseInt(jTextField1.getText());
}catch(NumberFormatException ex){ // handle your exception
                System.out.println("null qty value ERROR");
}
        
     int countz = 0;
    //buy
        if(jRadioButton1.isSelected()==true)
        {
         p=Float.parseFloat(price);
         qty=Integer.parseInt(jTextField1.getText());
         bal=bal-(p*qty);
         //u_id = id;
         if(bal>=0){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate localDate = LocalDate.now();
        
        jTextField4.setText(""+bal);
        String dop = dtf.format(localDate);
        String price1 = price + "";  
         try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql="insert into portfolio(ID,sID,qty,p_price,dop) values('"+uid+"','"+s_id+"','"+qty+"','"+price1+"','"+dop+"')";
    stmt.executeQuery(sql);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
         try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    Statement stmt1=con.createStatement();
    String sql2="update userDetail set balance='"+bal+"' where id='"+uid+"'";
    stmt1.executeUpdate(sql2);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
         }
         else{
             System.out.println("insufficient balance !!");
         }
     }   
        //sell 
        
    if(jRadioButton2.isSelected()==true)
    {
        p=Float.parseFloat(price);
       qty=Integer.parseInt(jTextField1.getText());
      bal=bal+(p*qty);
      DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate localDate = LocalDate.now();
        System.out.println("stock.exchang"+bal);
        jTextField4.setText(""+bal);
        String dop = dtf.format(localDate);
        String price1 = price + "";
        
        //error check
    try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt4=con.createStatement();
    String sql4="select sum(qty) as sm from portfolio where ID='"+uid+"'and sID='"+s_id+"' group by sID";
    ResultSet rs33 = stmt4.executeQuery(sql4);
    while(rs33.next()){
         countz = rs33.getInt("sm");
         System.out.println("qty selected:"+qty+"available :"+countz);
    }
     }
     catch(Exception e){
           System.out.println(e.getMessage());
     }
      if(countz < qty){
            System.out.println("incorrect qty"+ "entered : "+ countz +"max: "+qty);
        }else{  
      try
      {
          Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt=con.createStatement();
    String sql="insert into portfolio(ID,sID,qty,p_price,dop) values('"+uid+"','"+s_id+"','-"+qty+"','"+price1+"','"+dop+"')";
    stmt.executeQuery(sql);
      }
      catch(Exception e)
      {
          System.out.println(e.getMessage());
      }
         try{
             
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt1=con.createStatement();
    String sql2="update userDetail set balance='"+bal+"' where id='"+uid+"'";
    System.out.println("updating"+bal+"  ");
    stmt1.executeUpdate(sql2);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
         
         try{
             
    Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection)DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=stock1;user=root;password=dbpass");
    Statement stmt2=con.createStatement();
    String sql22="delete from portfolio where sID in (select sID from portfolio where ID ='"+uid+"' group by sID having sum(qty) = 0);";
             
    stmt2.executeUpdate(sql22);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        } 
    }
    }      }
//TODO add your handling code here
    }//GEN-LAST:event_resActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MainScreen(uid).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             // new MainScreen(1).setVisible(true);
              
            }
        });
        
        
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton res;
    // End of variables declaration//GEN-END:variables
}




